#  Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Example:

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        counts = {}
        for x in s:
            if x not in counts:
                counts[x] = 1
            else:
                counts[x] += 1
        for y in t:
            if y in counts:
                counts[y] -= 1
                if counts[y] < 0:
                    return y
            else:
                return y

class Solution2(object):
    def findTheDifference(self, s, t):
        for c in set(t):
            if t.count(c) > s.count(c):
                return c
